version: '3.8'

services:
  listenarr:
    image: ghcr.io/listenarrs/listenarr:canary ## For Docker Hub, replace the image with docker.io/therobbiedavis/listenarr:canary
    user: "1001:1001"  ## Replace with your desired UID and GID
    ports:
      - "4545:4545"
    environment:
      # OPTIONAL: set logging level at runtime (overrides config file). Valid values: Verbose, Debug, Information, Warning, Error, Fatal
      # e.g. to enable debug logs in Docker: LISTENARR_LOG_LEVEL=Debug
      - LISTENARR_LOG_LEVEL=Information
      - LISTENARR_PUBLIC_URL=https://your-domain.com ## OPTIONAL: Used by Discord Bot
    volumes:
      - listenarr_data:/app/config
    restart: unless-stopped

  db-reset:
    image: ghcr.io/listenarrs/listenarr:canary
    profiles: ["tools"]
    volumes:
      - listenarr_data:/app/config
    entrypoint: sh
    command: -c "rm -f /app/config/listenarr.db && echo 'Database deleted.'"

volumes:
  listenarr_data:
